baseURL = "https://sofiaborga.github.io"
title = "Sofia's sandbox"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
copyright = "© 2020 Writing by  <a href='https://twitter.com/sofborga'>@sofborga</a> with <a href='https://github.com/siegerts/hugo-theme-basic'>Hugo Theme Basic</a> by <a href='https://twitter.com/siegerts'>@siegerts</a>."
description = "Testing testing"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":clap:"
  # change this!
  twitter = "sofborga"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true